# Generated by Django 5.1.7 on 2025-03-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_comment_complaint_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='severity',
            field=models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='MEDIUM', max_length=10),
        ),
    ]
