# Generated by Django 5.0 on 2023-12-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
