# Generated by Django 5.1.1 on 2024-09-10 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_device_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='device_token',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='home_language',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='id_number',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
